### ISSUE TITLE
jinja error

### ISSUE THREAD

**Issue by TinKurbatoff** [hkage/tornado-project-skeleton#12]
Got the following error (Ubuntu 20.04 LTS):
$ cookiecutter https://github.com/hkage/cookiecutter-tornado
author_name [Your name]: My Name
email [Your e-mail]: myname@gmail.com
project_name [project_name]: 
repo_name [project_name]: 
package_name [project_name]: 
github_username [yourname]: 
description [A short description of the project]: 
version [0.1.0]: 
python_versions [3.5,3.6,3.7,3.8]: 
Select use_pytest:
1 - Yes
2 - No
Choose from 1, 2 [1]: 
Select use_tox:
1 - Yes
2 - No
Choose from 1, 2 [1]: 
Select use_docker:
1 - Yes
2 - No
Choose from 1, 2 [1]: 
Select use_vagrant:
1 - Yes
2 - No
Choose from 1, 2 [1]: 
Select use_bumpversion:
1 - Yes
2 - No
Choose from 1, 2 [1]: 
Select use_i18n:
1 - Yes
2 - No
Choose from 1, 2 [1]: 
max_line_length [120]: 
Select open_source_license:
1 - MIT license
2 - BSD license
3 - ISC license
4 - Apache Software License 2.0
5 - GNU General Public License v3
6 - Not open source
Choose from 1, 2, 3, 4, 5, 6 [1]: 

And got the error:
```
Traceback (most recent call last):
  File "/home/welcome/.local/bin/cookiecutter", line 8, in <module>
    sys.exit(main())
  File "/home/welcome/.local/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/welcome/.local/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/welcome/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/welcome/.local/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/welcome/.local/lib/python3.8/site-packages/cookiecutter/cli.py", line 140, in main
    cookiecutter(
  File "/home/welcome/.local/lib/python3.8/site-packages/cookiecutter/main.py", line 101, in cookiecutter
    result = generate_files(
  File "/home/welcome/.local/lib/python3.8/site-packages/cookiecutter/generate.py", line 352, in generate_files
    generate_file(
  File "/home/welcome/.local/lib/python3.8/site-packages/cookiecutter/generate.py", line 169, in generate_file
    tmpl = env.get_template(infile_fwd_slashes)
  File "/home/welcome/.local/lib/python3.8/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/home/welcome/.local/lib/python3.8/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/welcome/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "/home/welcome/.local/lib/python3.8/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/home/welcome/.local/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "./setup.py", line 130, in template
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
  File "./setup.py", line 130
    {%- endif %}
 
```
I think the problem is here:
![image](https://user-images.githubusercontent.com/48193889/121607191-9a81eb00-ca1d-11eb-8e03-00013d79223a.png)

**Comment by hkage** [comment]
Hi, thanks for your reporting. Actually the Jinja template syntax was broken on line 126, due to the whitespaces within the `endif` tag. I will fix this in the development branch.

**Comment by hkage** [comment]
Fixed in https://github.com/hkage/cookiecutter-tornado/commit/2b84bf81f07e487346296bbff64de6374bf84d58

**Comment by TinKurbatoff** [comment]
Thank you!
will share if any improvement ideas. :-)
I love Tornado very much (even being pro in Django).

Happy coding,
Constantine.
